[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

# Denite
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'execute "source " . g:dein_base_dir . "/rc/denite.vim"'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'Shougo/neomru.vim'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'execute "source " . g:dein_base_dir . "/rc/lightline.vim"'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# editing
[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'vim-scripts/Align'

# devel
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'execute "source " . g:dein_base_dir . "/rc/syntastic.vim"'

[[plugins]]
repo = 'tpope/vim-fugitive'

# misc
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = 'execute "source " . g:dein_base_dir . "/rc/memolist.vim"'
